# KaraokeForge Configuration

# Audio
SAMPLE_RATE = 16000
NORMALIZE_HEADROOM_DB = -3.0

# Separation
DEMUCS_MODEL = "htdemucs"
DEMUCS_SHIFTS = 1
DEMUCS_OVERLAP = 0.25

# Alignment
WHISPER_MODEL = "large-v3"
WHISPER_LANGUAGE = "ru"
ALIGNMENT_MODEL = "wav2vec2-large-xlsr-53-russian"

# Pitch
CREPE_MODEL_CAPACITY = "full"
CREPE_STEP_SIZE_MS = 10
CREPE_CONFIDENCE_THRESHOLD = 0.5
PITCH_MIN_HZ = 65
PITCH_MAX_HZ = 2000

# Cleaning
MIN_NOTE_DURATION_MS = 50
MAX_GAP_FILL_MS = 100
MEDIAN_FILTER_WINDOW = 5

# Scoring
HIT_THRESHOLD_CENTS = 50
NOISE_GATE_RMS = 0.01
EVALUATION_INTERVAL_MS = 100

# Pauses
COUNTDOWN_MIN_DURATION_SEC = 2.0
COUNTDOWN_VALUES = ["3", "2", "1", "Пой!"]

# UI
WINDOW_MIN_WIDTH = 1024
WINDOW_MIN_HEIGHT = 768
